# Generated by Django 3.2.5 on 2021-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('depot_lat', models.DecimalField(decimal_places=15, max_digits=15)),
                ('deopt_long', models.DecimalField(decimal_places=15, max_digits=15)),
                ('inspector_zone', models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Al Ain', 'Al Ain'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman')], default='Abu Dhabi', max_length=10)),
                ('starting_time', models.DateField(blank=True)),
                ('finishing_time', models.TimeField(blank=True)),
                ('service_time', models.TimeField(blank=True)),
            ],
        ),
    ]
