# Generated by Django 3.2.5 on 2021-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211118_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deopt_long',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='depot_lat',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
