# Generated by Django 3.2.5 on 2021-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('destination_lat', models.DecimalField(decimal_places=15, max_digits=15)),
                ('destination_long', models.DecimalField(decimal_places=15, max_digits=15)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=6)),
                ('visiting_date', models.DateField(null=True)),
            ],
        ),
    ]
